config/routes.rb
Rails.application.routes.draw do

  root "artists#index"

  resources :songs
  resources :artists
  resources :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true, length: {maximum: 30}
  validates :bio, length: { maximum: 500 }, presence: true
  validates :image_url, length: { maximum: 255 }, allow_blank: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist, foreign_key: :artist_id, dependent: :destroy

  def self.order_by_name
    order(:name)
  end

  validates :name, presence: true, uniqueness: true, length: {maximum: 30}
  validates :duration, length: { maximum: 10 }, presence: true
  validates :genre, length: { maximum: 30 }, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)


    if @artist.save
      image_params.each do |image|
        @artist.photos.create(image: image)
      end

      redirect_to root_path(@artist), notice: "Artist successfully created"
    else
      render :new
    end
  end



  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist=Artist.find(params[:id])
    if @artist.destroy
    flash[:notice] ="Artist Deleted"
    redirect_to root_path
    else
    render "delete"
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :bio, :image_url)
    end

    private

    def image_params
      params[:images].present? ? params.require(:images) : []
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all

  end

  def new
    @song = Song.new
  end

  def show
   @song = Song.find(params[:id])
  end

  def create

    @song = Song.new(song_params)

    if @song.save
       redirect_to root_path(@song), notice: "Song successfully added"
    else
       render 'new'
    end
  end

  def destroy
    @song = Song.find(params[:id])

    @song.destroy

    redirect_to songs_path
  end

private

    def song_params
      params.require(:song).permit(:name, :duration, :genre, :artist_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>

  <div class="form-group">
  <span class="btn btn-default">
    Upload Photo
    <%= file_field_tag "images[]", type: :file, multiple: true %>
  </span>
  </div>

  <div class="actions">
    <%= f.submit  %>
  </div>


<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= link_to artist.name, artist_path(artist.id) %></td>

        <td><%= artist.bio %></td>
        <td><% artist.photos.each do |photo| %>
          <%= image_tag photo.image.thumbnail %>
        <%end%>
        </td>

        <td><%= link_to "[Delete Artist]", artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "[Add New Artist]", new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to '[All Artists]', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Songs</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration (in seconds)</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @artist.songs.any? %>
      <% @artist.songs.each do |song| %>
      <tr>
        <td><%= song.name %></td>
        <td><%= song.duration %></td>
        <td><%= song.genre %></td>
        <td><%= link_to "[Delete Song]", song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <% end %>
    <tr>
      <td><%= link_to "[Add New Song]", new_song_path %></td>
    </tr>
  </tbody>
</table>

<hr>


<%= link_to "[All Artists]", artists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>
        Codaisseurify
      </h1>
    </header>

    <%= yield %>

    <hr>


  </body>
</html>

app/views/songs/_form.html.erb
<h1>New Song</h1>

<%= form_for @song do |f| %>
  <ul>
    <% @song.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>


  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :duration %>
  <%= f.number_field :duration %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.label :artist_id %>
  <%= f.collection_select(:artist_id, Artist.all, :id, :name) %>


  <%= f.submit (@song.new_record? ? "Create" : "New") %>
  <br>
  <hr>
  <%= link_to '[All Artists]', artists_path %>
<% end %>

app/views/songs/index.html.erb
<%= link_to "[Add New Song]", new_song_path %>
<%= link_to "[All Artists]", artists_path %>

<hr>

<h1>Songs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Duration</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.name, song_path(song.id) %></td>
        <td><%= song.duration %></td>
        <td><%= song.genre %></td>
      </tr>
    <% end %>
  </tbody>

app/views/songs/new.html.erb
<%= render "form" %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @song.name %></h1>

<%= link_to "[All Songs]", songs_path %>

<%= link_to "[Delete Song]", song_path(@song.id), method: :delete, data: { confirm: "Are you sure?" } %>